//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SoruCevapServisi
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class sorununcevabiEntitiesDB : DbContext
    {
        public sorununcevabiEntitiesDB()
            : base("name=sorununcevabiEntitiesDB")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Cevaplar> Cevaplar { get; set; }
        public virtual DbSet<FavoriCevap> FavoriCevap { get; set; }
        public virtual DbSet<FavoriSoru> FavoriSoru { get; set; }
        public virtual DbSet<Sorular> Sorular { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<Uyeler> Uyeler { get; set; }
    }
}
