//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SoruCevapServisi
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sorular
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Sorular()
        {
            this.Cevaplar = new HashSet<Cevaplar>();
            this.FavoriSoru = new HashSet<FavoriSoru>();
        }
    
        public int soruID { get; set; }
        public string soruBasligi { get; set; }
        public string soruIcerigi { get; set; }
        public Nullable<int> soruSahibi { get; set; }
        public Nullable<System.DateTime> soruTarihi { get; set; }
        public Nullable<int> favori { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Cevaplar> Cevaplar { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FavoriSoru> FavoriSoru { get; set; }
        public virtual Uyeler Uyeler { get; set; }
    }
}
