//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SorununCevabi.ServiceReference {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Cevap", Namespace="http://schemas.datacontract.org/2004/07/SoruCevapServisi")]
    [System.SerializableAttribute()]
    public partial class Cevap : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string BaslikField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IcerikField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int cevapIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string cevapSahibiField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int cevapSahibiIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime cevapTarihiField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string cevapciresmiField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool favoriField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool faydalimiField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int soruNoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Collections.Generic.List<SorununCevabi.ServiceReference.Yorum> yorumlarField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Baslik {
            get {
                return this.BaslikField;
            }
            set {
                if ((object.ReferenceEquals(this.BaslikField, value) != true)) {
                    this.BaslikField = value;
                    this.RaisePropertyChanged("Baslik");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Icerik {
            get {
                return this.IcerikField;
            }
            set {
                if ((object.ReferenceEquals(this.IcerikField, value) != true)) {
                    this.IcerikField = value;
                    this.RaisePropertyChanged("Icerik");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int cevapID {
            get {
                return this.cevapIDField;
            }
            set {
                if ((this.cevapIDField.Equals(value) != true)) {
                    this.cevapIDField = value;
                    this.RaisePropertyChanged("cevapID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string cevapSahibi {
            get {
                return this.cevapSahibiField;
            }
            set {
                if ((object.ReferenceEquals(this.cevapSahibiField, value) != true)) {
                    this.cevapSahibiField = value;
                    this.RaisePropertyChanged("cevapSahibi");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int cevapSahibiID {
            get {
                return this.cevapSahibiIDField;
            }
            set {
                if ((this.cevapSahibiIDField.Equals(value) != true)) {
                    this.cevapSahibiIDField = value;
                    this.RaisePropertyChanged("cevapSahibiID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime cevapTarihi {
            get {
                return this.cevapTarihiField;
            }
            set {
                if ((this.cevapTarihiField.Equals(value) != true)) {
                    this.cevapTarihiField = value;
                    this.RaisePropertyChanged("cevapTarihi");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string cevapciresmi {
            get {
                return this.cevapciresmiField;
            }
            set {
                if ((object.ReferenceEquals(this.cevapciresmiField, value) != true)) {
                    this.cevapciresmiField = value;
                    this.RaisePropertyChanged("cevapciresmi");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool favori {
            get {
                return this.favoriField;
            }
            set {
                if ((this.favoriField.Equals(value) != true)) {
                    this.favoriField = value;
                    this.RaisePropertyChanged("favori");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool faydalimi {
            get {
                return this.faydalimiField;
            }
            set {
                if ((this.faydalimiField.Equals(value) != true)) {
                    this.faydalimiField = value;
                    this.RaisePropertyChanged("faydalimi");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int soruNo {
            get {
                return this.soruNoField;
            }
            set {
                if ((this.soruNoField.Equals(value) != true)) {
                    this.soruNoField = value;
                    this.RaisePropertyChanged("soruNo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.List<SorununCevabi.ServiceReference.Yorum> yorumlar {
            get {
                return this.yorumlarField;
            }
            set {
                if ((object.ReferenceEquals(this.yorumlarField, value) != true)) {
                    this.yorumlarField = value;
                    this.RaisePropertyChanged("yorumlar");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Yorum", Namespace="http://schemas.datacontract.org/2004/07/SoruCevapServisi")]
    [System.SerializableAttribute()]
    public partial class Yorum : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string BaslikField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IcerikField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int cevapIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string yorumSahibiField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int yorumSahibiIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime yorumTarihiField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string yorumcuadiField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string yorumcuresmiField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string yorumcusoyadiField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Baslik {
            get {
                return this.BaslikField;
            }
            set {
                if ((object.ReferenceEquals(this.BaslikField, value) != true)) {
                    this.BaslikField = value;
                    this.RaisePropertyChanged("Baslik");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Icerik {
            get {
                return this.IcerikField;
            }
            set {
                if ((object.ReferenceEquals(this.IcerikField, value) != true)) {
                    this.IcerikField = value;
                    this.RaisePropertyChanged("Icerik");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int cevapID {
            get {
                return this.cevapIDField;
            }
            set {
                if ((this.cevapIDField.Equals(value) != true)) {
                    this.cevapIDField = value;
                    this.RaisePropertyChanged("cevapID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string yorumSahibi {
            get {
                return this.yorumSahibiField;
            }
            set {
                if ((object.ReferenceEquals(this.yorumSahibiField, value) != true)) {
                    this.yorumSahibiField = value;
                    this.RaisePropertyChanged("yorumSahibi");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int yorumSahibiID {
            get {
                return this.yorumSahibiIDField;
            }
            set {
                if ((this.yorumSahibiIDField.Equals(value) != true)) {
                    this.yorumSahibiIDField = value;
                    this.RaisePropertyChanged("yorumSahibiID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime yorumTarihi {
            get {
                return this.yorumTarihiField;
            }
            set {
                if ((this.yorumTarihiField.Equals(value) != true)) {
                    this.yorumTarihiField = value;
                    this.RaisePropertyChanged("yorumTarihi");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string yorumcuadi {
            get {
                return this.yorumcuadiField;
            }
            set {
                if ((object.ReferenceEquals(this.yorumcuadiField, value) != true)) {
                    this.yorumcuadiField = value;
                    this.RaisePropertyChanged("yorumcuadi");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string yorumcuresmi {
            get {
                return this.yorumcuresmiField;
            }
            set {
                if ((object.ReferenceEquals(this.yorumcuresmiField, value) != true)) {
                    this.yorumcuresmiField = value;
                    this.RaisePropertyChanged("yorumcuresmi");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string yorumcusoyadi {
            get {
                return this.yorumcusoyadiField;
            }
            set {
                if ((object.ReferenceEquals(this.yorumcusoyadiField, value) != true)) {
                    this.yorumcusoyadiField = value;
                    this.RaisePropertyChanged("yorumcusoyadi");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Soru", Namespace="http://schemas.datacontract.org/2004/07/SoruCevapServisi")]
    [System.SerializableAttribute()]
    public partial class Soru : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool favoriField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string soruBasligiField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int soruIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string soruIcerigiField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string soruSahibiField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int soruSahibiIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string soruSahibiResimField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime soruTarihiField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool favori {
            get {
                return this.favoriField;
            }
            set {
                if ((this.favoriField.Equals(value) != true)) {
                    this.favoriField = value;
                    this.RaisePropertyChanged("favori");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string soruBasligi {
            get {
                return this.soruBasligiField;
            }
            set {
                if ((object.ReferenceEquals(this.soruBasligiField, value) != true)) {
                    this.soruBasligiField = value;
                    this.RaisePropertyChanged("soruBasligi");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int soruID {
            get {
                return this.soruIDField;
            }
            set {
                if ((this.soruIDField.Equals(value) != true)) {
                    this.soruIDField = value;
                    this.RaisePropertyChanged("soruID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string soruIcerigi {
            get {
                return this.soruIcerigiField;
            }
            set {
                if ((object.ReferenceEquals(this.soruIcerigiField, value) != true)) {
                    this.soruIcerigiField = value;
                    this.RaisePropertyChanged("soruIcerigi");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string soruSahibi {
            get {
                return this.soruSahibiField;
            }
            set {
                if ((object.ReferenceEquals(this.soruSahibiField, value) != true)) {
                    this.soruSahibiField = value;
                    this.RaisePropertyChanged("soruSahibi");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int soruSahibiID {
            get {
                return this.soruSahibiIDField;
            }
            set {
                if ((this.soruSahibiIDField.Equals(value) != true)) {
                    this.soruSahibiIDField = value;
                    this.RaisePropertyChanged("soruSahibiID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string soruSahibiResim {
            get {
                return this.soruSahibiResimField;
            }
            set {
                if ((object.ReferenceEquals(this.soruSahibiResimField, value) != true)) {
                    this.soruSahibiResimField = value;
                    this.RaisePropertyChanged("soruSahibiResim");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime soruTarihi {
            get {
                return this.soruTarihiField;
            }
            set {
                if ((this.soruTarihiField.Equals(value) != true)) {
                    this.soruTarihiField = value;
                    this.RaisePropertyChanged("soruTarihi");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Uye", Namespace="http://schemas.datacontract.org/2004/07/SoruCevapServisi")]
    [System.SerializableAttribute()]
    public partial class Uye : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int UyeIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string adiField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string egitimField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string epostaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime kayittarihiField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string konumField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string kuladiField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string kullaniciresmiField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string meslekField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string notField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string sifreField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string soyadiField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string yetenekField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int UyeID {
            get {
                return this.UyeIDField;
            }
            set {
                if ((this.UyeIDField.Equals(value) != true)) {
                    this.UyeIDField = value;
                    this.RaisePropertyChanged("UyeID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string adi {
            get {
                return this.adiField;
            }
            set {
                if ((object.ReferenceEquals(this.adiField, value) != true)) {
                    this.adiField = value;
                    this.RaisePropertyChanged("adi");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string egitim {
            get {
                return this.egitimField;
            }
            set {
                if ((object.ReferenceEquals(this.egitimField, value) != true)) {
                    this.egitimField = value;
                    this.RaisePropertyChanged("egitim");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string eposta {
            get {
                return this.epostaField;
            }
            set {
                if ((object.ReferenceEquals(this.epostaField, value) != true)) {
                    this.epostaField = value;
                    this.RaisePropertyChanged("eposta");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime kayittarihi {
            get {
                return this.kayittarihiField;
            }
            set {
                if ((this.kayittarihiField.Equals(value) != true)) {
                    this.kayittarihiField = value;
                    this.RaisePropertyChanged("kayittarihi");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string konum {
            get {
                return this.konumField;
            }
            set {
                if ((object.ReferenceEquals(this.konumField, value) != true)) {
                    this.konumField = value;
                    this.RaisePropertyChanged("konum");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string kuladi {
            get {
                return this.kuladiField;
            }
            set {
                if ((object.ReferenceEquals(this.kuladiField, value) != true)) {
                    this.kuladiField = value;
                    this.RaisePropertyChanged("kuladi");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string kullaniciresmi {
            get {
                return this.kullaniciresmiField;
            }
            set {
                if ((object.ReferenceEquals(this.kullaniciresmiField, value) != true)) {
                    this.kullaniciresmiField = value;
                    this.RaisePropertyChanged("kullaniciresmi");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string meslek {
            get {
                return this.meslekField;
            }
            set {
                if ((object.ReferenceEquals(this.meslekField, value) != true)) {
                    this.meslekField = value;
                    this.RaisePropertyChanged("meslek");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string not {
            get {
                return this.notField;
            }
            set {
                if ((object.ReferenceEquals(this.notField, value) != true)) {
                    this.notField = value;
                    this.RaisePropertyChanged("not");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string sifre {
            get {
                return this.sifreField;
            }
            set {
                if ((object.ReferenceEquals(this.sifreField, value) != true)) {
                    this.sifreField = value;
                    this.RaisePropertyChanged("sifre");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string soyadi {
            get {
                return this.soyadiField;
            }
            set {
                if ((object.ReferenceEquals(this.soyadiField, value) != true)) {
                    this.soyadiField = value;
                    this.RaisePropertyChanged("soyadi");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string yetenek {
            get {
                return this.yetenekField;
            }
            set {
                if ((object.ReferenceEquals(this.yetenekField, value) != true)) {
                    this.yetenekField = value;
                    this.RaisePropertyChanged("yetenek");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference.ISorununCevabi")]
    public interface ISorununCevabi {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISorununCevabi/giris", ReplyAction="http://tempuri.org/ISorununCevabi/girisResponse")]
        int giris(string kullaniciadi, string sifre);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISorununCevabi/giris", ReplyAction="http://tempuri.org/ISorununCevabi/girisResponse")]
        System.Threading.Tasks.Task<int> girisAsync(string kullaniciadi, string sifre);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISorununCevabi/kayit", ReplyAction="http://tempuri.org/ISorununCevabi/kayitResponse")]
        int kayit(string kullaniciadi, string ad, string soyad, string sifre, string eposta, string kullaniciresmi, string meslek);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISorununCevabi/kayit", ReplyAction="http://tempuri.org/ISorununCevabi/kayitResponse")]
        System.Threading.Tasks.Task<int> kayitAsync(string kullaniciadi, string ad, string soyad, string sifre, string eposta, string kullaniciresmi, string meslek);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISorununCevabi/soruekle", ReplyAction="http://tempuri.org/ISorununCevabi/soruekleResponse")]
        bool soruekle(string soruBasligi, string soruIcerigi, int soruSahibi, System.DateTime soruTarihi, int favori);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISorununCevabi/soruekle", ReplyAction="http://tempuri.org/ISorununCevabi/soruekleResponse")]
        System.Threading.Tasks.Task<bool> soruekleAsync(string soruBasligi, string soruIcerigi, int soruSahibi, System.DateTime soruTarihi, int favori);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISorununCevabi/cevapekle", ReplyAction="http://tempuri.org/ISorununCevabi/cevapekleResponse")]
        bool cevapekle(string cevapBasligi, string cevapİcerigi, int cevapSahibi, int soruNo, int yorumID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISorununCevabi/cevapekle", ReplyAction="http://tempuri.org/ISorununCevabi/cevapekleResponse")]
        System.Threading.Tasks.Task<bool> cevapekleAsync(string cevapBasligi, string cevapİcerigi, int cevapSahibi, int soruNo, int yorumID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISorununCevabi/cevapfavekle", ReplyAction="http://tempuri.org/ISorununCevabi/cevapfavekleResponse")]
        bool cevapfavekle(int uyeID, int cevapID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISorununCevabi/cevapfavekle", ReplyAction="http://tempuri.org/ISorununCevabi/cevapfavekleResponse")]
        System.Threading.Tasks.Task<bool> cevapfavekleAsync(int uyeID, int cevapID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISorununCevabi/cevapcek", ReplyAction="http://tempuri.org/ISorununCevabi/cevapcekResponse")]
        System.Collections.Generic.List<SorununCevabi.ServiceReference.Cevap> cevapcek(int soruID, int uyeID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISorununCevabi/cevapcek", ReplyAction="http://tempuri.org/ISorununCevabi/cevapcekResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<SorununCevabi.ServiceReference.Cevap>> cevapcekAsync(int soruID, int uyeID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISorununCevabi/teksorucek", ReplyAction="http://tempuri.org/ISorununCevabi/teksorucekResponse")]
        SorununCevabi.ServiceReference.Soru teksorucek(int soruID, int uyeId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISorununCevabi/teksorucek", ReplyAction="http://tempuri.org/ISorununCevabi/teksorucekResponse")]
        System.Threading.Tasks.Task<SorununCevabi.ServiceReference.Soru> teksorucekAsync(int soruID, int uyeId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISorununCevabi/tumsorularıcek", ReplyAction="http://tempuri.org/ISorununCevabi/tumsorularıcekResponse")]
        System.Collections.Generic.List<SorununCevabi.ServiceReference.Soru> tumsorularıcek(int uyeID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISorununCevabi/tumsorularıcek", ReplyAction="http://tempuri.org/ISorununCevabi/tumsorularıcekResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<SorununCevabi.ServiceReference.Soru>> tumsorularıcekAsync(int uyeID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISorununCevabi/uyebilgileri", ReplyAction="http://tempuri.org/ISorununCevabi/uyebilgileriResponse")]
        SorununCevabi.ServiceReference.Uye uyebilgileri(int uyeID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISorununCevabi/uyebilgileri", ReplyAction="http://tempuri.org/ISorununCevabi/uyebilgileriResponse")]
        System.Threading.Tasks.Task<SorununCevabi.ServiceReference.Uye> uyebilgileriAsync(int uyeID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISorununCevabi/sorusil", ReplyAction="http://tempuri.org/ISorununCevabi/sorusilResponse")]
        bool sorusil(int soruid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISorununCevabi/sorusil", ReplyAction="http://tempuri.org/ISorununCevabi/sorusilResponse")]
        System.Threading.Tasks.Task<bool> sorusilAsync(int soruid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISorununCevabi/soruguncelle", ReplyAction="http://tempuri.org/ISorununCevabi/soruguncelleResponse")]
        bool soruguncelle(int soruid, string sorubaslik, string soruicerik);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISorununCevabi/soruguncelle", ReplyAction="http://tempuri.org/ISorununCevabi/soruguncelleResponse")]
        System.Threading.Tasks.Task<bool> soruguncelleAsync(int soruid, string sorubaslik, string soruicerik);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISorununCevabi/cevapsil", ReplyAction="http://tempuri.org/ISorununCevabi/cevapsilResponse")]
        bool cevapsil(int cevapid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISorununCevabi/cevapsil", ReplyAction="http://tempuri.org/ISorununCevabi/cevapsilResponse")]
        System.Threading.Tasks.Task<bool> cevapsilAsync(int cevapid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISorununCevabi/sorufavguncelle", ReplyAction="http://tempuri.org/ISorununCevabi/sorufavguncelleResponse")]
        bool sorufavguncelle(int uyeID, int soruID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISorununCevabi/sorufavguncelle", ReplyAction="http://tempuri.org/ISorununCevabi/sorufavguncelleResponse")]
        System.Threading.Tasks.Task<bool> sorufavguncelleAsync(int uyeID, int soruID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISorununCevabi/cevapfavguncelle", ReplyAction="http://tempuri.org/ISorununCevabi/cevapfavguncelleResponse")]
        bool cevapfavguncelle(int uyeID, int soruID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISorununCevabi/cevapfavguncelle", ReplyAction="http://tempuri.org/ISorununCevabi/cevapfavguncelleResponse")]
        System.Threading.Tasks.Task<bool> cevapfavguncelleAsync(int uyeID, int soruID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISorununCevabi/yararlicevap", ReplyAction="http://tempuri.org/ISorununCevabi/yararlicevapResponse")]
        bool yararlicevap(int cevapID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISorununCevabi/yararlicevap", ReplyAction="http://tempuri.org/ISorununCevabi/yararlicevapResponse")]
        System.Threading.Tasks.Task<bool> yararlicevapAsync(int cevapID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISorununCevabi/tumfavorisorularıcek", ReplyAction="http://tempuri.org/ISorununCevabi/tumfavorisorularıcekResponse")]
        System.Collections.Generic.List<SorununCevabi.ServiceReference.Soru> tumfavorisorularıcek(int uyeID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISorununCevabi/tumfavorisorularıcek", ReplyAction="http://tempuri.org/ISorununCevabi/tumfavorisorularıcekResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<SorununCevabi.ServiceReference.Soru>> tumfavorisorularıcekAsync(int uyeID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISorununCevabi/tumfavoricevaplaricek", ReplyAction="http://tempuri.org/ISorununCevabi/tumfavoricevaplaricekResponse")]
        System.Collections.Generic.List<SorununCevabi.ServiceReference.Cevap> tumfavoricevaplaricek(int uyeID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISorununCevabi/tumfavoricevaplaricek", ReplyAction="http://tempuri.org/ISorununCevabi/tumfavoricevaplaricekResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<SorununCevabi.ServiceReference.Cevap>> tumfavoricevaplaricekAsync(int uyeID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISorununCevabi/kulSoruSayisi", ReplyAction="http://tempuri.org/ISorununCevabi/kulSoruSayisiResponse")]
        int kulSoruSayisi(int uyeID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISorununCevabi/kulSoruSayisi", ReplyAction="http://tempuri.org/ISorununCevabi/kulSoruSayisiResponse")]
        System.Threading.Tasks.Task<int> kulSoruSayisiAsync(int uyeID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISorununCevabi/kulCevapSayisi", ReplyAction="http://tempuri.org/ISorununCevabi/kulCevapSayisiResponse")]
        int kulCevapSayisi(int uyeID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISorununCevabi/kulCevapSayisi", ReplyAction="http://tempuri.org/ISorununCevabi/kulCevapSayisiResponse")]
        System.Threading.Tasks.Task<int> kulCevapSayisiAsync(int uyeID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISorununCevabi/kulFavSoruSayisi", ReplyAction="http://tempuri.org/ISorununCevabi/kulFavSoruSayisiResponse")]
        int kulFavSoruSayisi(int uyeID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISorununCevabi/kulFavSoruSayisi", ReplyAction="http://tempuri.org/ISorununCevabi/kulFavSoruSayisiResponse")]
        System.Threading.Tasks.Task<int> kulFavSoruSayisiAsync(int uyeID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISorununCevabi/kulFavCevapSayisi", ReplyAction="http://tempuri.org/ISorununCevabi/kulFavCevapSayisiResponse")]
        int kulFavCevapSayisi(int uyeID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISorununCevabi/kulFavCevapSayisi", ReplyAction="http://tempuri.org/ISorununCevabi/kulFavCevapSayisiResponse")]
        System.Threading.Tasks.Task<int> kulFavCevapSayisiAsync(int uyeID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISorununCevabi/profilGuncelle", ReplyAction="http://tempuri.org/ISorununCevabi/profilGuncelleResponse")]
        bool profilGuncelle(SorununCevabi.ServiceReference.Uye uye);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISorununCevabi/profilGuncelle", ReplyAction="http://tempuri.org/ISorununCevabi/profilGuncelleResponse")]
        System.Threading.Tasks.Task<bool> profilGuncelleAsync(SorununCevabi.ServiceReference.Uye uye);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISorununCevabi/tumuyelericek", ReplyAction="http://tempuri.org/ISorununCevabi/tumuyelericekResponse")]
        System.Collections.Generic.List<SorununCevabi.ServiceReference.Uye> tumuyelericek();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISorununCevabi/tumuyelericek", ReplyAction="http://tempuri.org/ISorununCevabi/tumuyelericekResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<SorununCevabi.ServiceReference.Uye>> tumuyelericekAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ISorununCevabiChannel : SorununCevabi.ServiceReference.ISorununCevabi, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SorununCevabiClient : System.ServiceModel.ClientBase<SorununCevabi.ServiceReference.ISorununCevabi>, SorununCevabi.ServiceReference.ISorununCevabi {
        
        public SorununCevabiClient() {
        }
        
        public SorununCevabiClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SorununCevabiClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SorununCevabiClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SorununCevabiClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public int giris(string kullaniciadi, string sifre) {
            return base.Channel.giris(kullaniciadi, sifre);
        }
        
        public System.Threading.Tasks.Task<int> girisAsync(string kullaniciadi, string sifre) {
            return base.Channel.girisAsync(kullaniciadi, sifre);
        }
        
        public int kayit(string kullaniciadi, string ad, string soyad, string sifre, string eposta, string kullaniciresmi, string meslek) {
            return base.Channel.kayit(kullaniciadi, ad, soyad, sifre, eposta, kullaniciresmi, meslek);
        }
        
        public System.Threading.Tasks.Task<int> kayitAsync(string kullaniciadi, string ad, string soyad, string sifre, string eposta, string kullaniciresmi, string meslek) {
            return base.Channel.kayitAsync(kullaniciadi, ad, soyad, sifre, eposta, kullaniciresmi, meslek);
        }
        
        public bool soruekle(string soruBasligi, string soruIcerigi, int soruSahibi, System.DateTime soruTarihi, int favori) {
            return base.Channel.soruekle(soruBasligi, soruIcerigi, soruSahibi, soruTarihi, favori);
        }
        
        public System.Threading.Tasks.Task<bool> soruekleAsync(string soruBasligi, string soruIcerigi, int soruSahibi, System.DateTime soruTarihi, int favori) {
            return base.Channel.soruekleAsync(soruBasligi, soruIcerigi, soruSahibi, soruTarihi, favori);
        }
        
        public bool cevapekle(string cevapBasligi, string cevapİcerigi, int cevapSahibi, int soruNo, int yorumID) {
            return base.Channel.cevapekle(cevapBasligi, cevapİcerigi, cevapSahibi, soruNo, yorumID);
        }
        
        public System.Threading.Tasks.Task<bool> cevapekleAsync(string cevapBasligi, string cevapİcerigi, int cevapSahibi, int soruNo, int yorumID) {
            return base.Channel.cevapekleAsync(cevapBasligi, cevapİcerigi, cevapSahibi, soruNo, yorumID);
        }
        
        public bool cevapfavekle(int uyeID, int cevapID) {
            return base.Channel.cevapfavekle(uyeID, cevapID);
        }
        
        public System.Threading.Tasks.Task<bool> cevapfavekleAsync(int uyeID, int cevapID) {
            return base.Channel.cevapfavekleAsync(uyeID, cevapID);
        }
        
        public System.Collections.Generic.List<SorununCevabi.ServiceReference.Cevap> cevapcek(int soruID, int uyeID) {
            return base.Channel.cevapcek(soruID, uyeID);
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<SorununCevabi.ServiceReference.Cevap>> cevapcekAsync(int soruID, int uyeID) {
            return base.Channel.cevapcekAsync(soruID, uyeID);
        }
        
        public SorununCevabi.ServiceReference.Soru teksorucek(int soruID, int uyeId) {
            return base.Channel.teksorucek(soruID, uyeId);
        }
        
        public System.Threading.Tasks.Task<SorununCevabi.ServiceReference.Soru> teksorucekAsync(int soruID, int uyeId) {
            return base.Channel.teksorucekAsync(soruID, uyeId);
        }
        
        public System.Collections.Generic.List<SorununCevabi.ServiceReference.Soru> tumsorularıcek(int uyeID) {
            return base.Channel.tumsorularıcek(uyeID);
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<SorununCevabi.ServiceReference.Soru>> tumsorularıcekAsync(int uyeID) {
            return base.Channel.tumsorularıcekAsync(uyeID);
        }
        
        public SorununCevabi.ServiceReference.Uye uyebilgileri(int uyeID) {
            return base.Channel.uyebilgileri(uyeID);
        }
        
        public System.Threading.Tasks.Task<SorununCevabi.ServiceReference.Uye> uyebilgileriAsync(int uyeID) {
            return base.Channel.uyebilgileriAsync(uyeID);
        }
        
        public bool sorusil(int soruid) {
            return base.Channel.sorusil(soruid);
        }
        
        public System.Threading.Tasks.Task<bool> sorusilAsync(int soruid) {
            return base.Channel.sorusilAsync(soruid);
        }
        
        public bool soruguncelle(int soruid, string sorubaslik, string soruicerik) {
            return base.Channel.soruguncelle(soruid, sorubaslik, soruicerik);
        }
        
        public System.Threading.Tasks.Task<bool> soruguncelleAsync(int soruid, string sorubaslik, string soruicerik) {
            return base.Channel.soruguncelleAsync(soruid, sorubaslik, soruicerik);
        }
        
        public bool cevapsil(int cevapid) {
            return base.Channel.cevapsil(cevapid);
        }
        
        public System.Threading.Tasks.Task<bool> cevapsilAsync(int cevapid) {
            return base.Channel.cevapsilAsync(cevapid);
        }
        
        public bool sorufavguncelle(int uyeID, int soruID) {
            return base.Channel.sorufavguncelle(uyeID, soruID);
        }
        
        public System.Threading.Tasks.Task<bool> sorufavguncelleAsync(int uyeID, int soruID) {
            return base.Channel.sorufavguncelleAsync(uyeID, soruID);
        }
        
        public bool cevapfavguncelle(int uyeID, int soruID) {
            return base.Channel.cevapfavguncelle(uyeID, soruID);
        }
        
        public System.Threading.Tasks.Task<bool> cevapfavguncelleAsync(int uyeID, int soruID) {
            return base.Channel.cevapfavguncelleAsync(uyeID, soruID);
        }
        
        public bool yararlicevap(int cevapID) {
            return base.Channel.yararlicevap(cevapID);
        }
        
        public System.Threading.Tasks.Task<bool> yararlicevapAsync(int cevapID) {
            return base.Channel.yararlicevapAsync(cevapID);
        }
        
        public System.Collections.Generic.List<SorununCevabi.ServiceReference.Soru> tumfavorisorularıcek(int uyeID) {
            return base.Channel.tumfavorisorularıcek(uyeID);
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<SorununCevabi.ServiceReference.Soru>> tumfavorisorularıcekAsync(int uyeID) {
            return base.Channel.tumfavorisorularıcekAsync(uyeID);
        }
        
        public System.Collections.Generic.List<SorununCevabi.ServiceReference.Cevap> tumfavoricevaplaricek(int uyeID) {
            return base.Channel.tumfavoricevaplaricek(uyeID);
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<SorununCevabi.ServiceReference.Cevap>> tumfavoricevaplaricekAsync(int uyeID) {
            return base.Channel.tumfavoricevaplaricekAsync(uyeID);
        }
        
        public int kulSoruSayisi(int uyeID) {
            return base.Channel.kulSoruSayisi(uyeID);
        }
        
        public System.Threading.Tasks.Task<int> kulSoruSayisiAsync(int uyeID) {
            return base.Channel.kulSoruSayisiAsync(uyeID);
        }
        
        public int kulCevapSayisi(int uyeID) {
            return base.Channel.kulCevapSayisi(uyeID);
        }
        
        public System.Threading.Tasks.Task<int> kulCevapSayisiAsync(int uyeID) {
            return base.Channel.kulCevapSayisiAsync(uyeID);
        }
        
        public int kulFavSoruSayisi(int uyeID) {
            return base.Channel.kulFavSoruSayisi(uyeID);
        }
        
        public System.Threading.Tasks.Task<int> kulFavSoruSayisiAsync(int uyeID) {
            return base.Channel.kulFavSoruSayisiAsync(uyeID);
        }
        
        public int kulFavCevapSayisi(int uyeID) {
            return base.Channel.kulFavCevapSayisi(uyeID);
        }
        
        public System.Threading.Tasks.Task<int> kulFavCevapSayisiAsync(int uyeID) {
            return base.Channel.kulFavCevapSayisiAsync(uyeID);
        }
        
        public bool profilGuncelle(SorununCevabi.ServiceReference.Uye uye) {
            return base.Channel.profilGuncelle(uye);
        }
        
        public System.Threading.Tasks.Task<bool> profilGuncelleAsync(SorununCevabi.ServiceReference.Uye uye) {
            return base.Channel.profilGuncelleAsync(uye);
        }
        
        public System.Collections.Generic.List<SorununCevabi.ServiceReference.Uye> tumuyelericek() {
            return base.Channel.tumuyelericek();
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<SorununCevabi.ServiceReference.Uye>> tumuyelericekAsync() {
            return base.Channel.tumuyelericekAsync();
        }
    }
}
